# Find markdown files (including blog posts, excluding templates)
# Use recursively expanded variable so it picks up generated index.md
# Also explicitly include src/index.md if it exists (generated by blog index)
SRC_MD = $(shell find src -type f -name "*.md" ! -name "*.template.md") $(wildcard src/index.md)

# Map to docs
OUT_HTML = $(patsubst src/%.md,docs/%.html,$(SRC_MD))

CSS_SRC := style.css
CSS_DST := docs/style.css

CSS := /style.css

# Blog-related variables
BLOG_DIR := src/blog
BLOG_INDEX_TEMPLATE := src/index.template.md
BLOG_INDEX_OUTPUT := src/index.md
GENERATOR_SCRIPT := scripts/generate-blog-index.py

# Default target
all: $(CSS_DST) $(BLOG_INDEX_OUTPUT) $(OUT_HTML) media-copy

# Generate blog index before building
INSERT_SCRIPT := scripts/insert_blog_listing.py
$(BLOG_INDEX_OUTPUT): $(BLOG_INDEX_TEMPLATE) $(GENERATOR_SCRIPT) $(INSERT_SCRIPT)
	@mkdir -p scripts
	@mkdir -p $(BLOG_DIR)
	python3 $(GENERATOR_SCRIPT) > $(BLOG_INDEX_OUTPUT).tmp
	python3 $(INSERT_SCRIPT) $(BLOG_INDEX_TEMPLATE) $(BLOG_INDEX_OUTPUT).tmp $(BLOG_INDEX_OUTPUT)
	@rm -f $(BLOG_INDEX_OUTPUT).tmp

# Copy CSS once
$(CSS_DST): $(CSS_SRC)
	@mkdir -p docs
	cp $(CSS_SRC) $(CSS_DST)

# Convert markdown to HTML (depends on generated index)
docs/%.html: src/%.md | $(CSS_DST)
	@mkdir -p $(dir $@)
	pandoc $< -o $@ -s --css=$(CSS) --lua-filter=md-to-html-links.lua

# Copy media files (images, videos, audio, etc.) preserving directory structure
media-copy:
	rsync -av --exclude='*.md' --exclude='*.template.md' src/ docs/

# Clean
clean:
	rm -rf docs
	rm -f $(BLOG_INDEX_OUTPUT)

.PHONY: all clean media-copy
